version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: python:3.9-slim
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      DATABASE_HOST: db
    command: ["python", "app.py"]
    depends_on:
      db:
        condition: service_healthy