# Utiliser une image de base avec Python
FROM python:3.9-slim

# Installer Flask
RUN pip install flask

# Copier le fichier app.py dans l'image
COPY app.py /app.py

# Exposer le port 5000
EXPOSE 8080

# Commande pour lancer le serveur
CMD ["python", "/app.py"]